language: node_js
node_js:
  - 'stable'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always